apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../k8s/
images:
- digest: sha256:c69109861be82594f726f92f83c2bfb364c1dbfba4355a3216e699e0f58f1e36
  name: quay.io/rh-ee-ksreeniv/dotnetcore
  newName: quay.io/rh-ee-ksreeniv/dotnetcore
