apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../k8s/
images:
- digest: sha256:687924f2a9ee69304c1a7d47b82504a19fb1460919830ae9e6042d0b94b939ea
  name: quay.io/rh-ee-ksreeniv/dotnetcore
  newName: quay.io/rh-ee-ksreeniv/dotnetcore
